name: Cypress Tests

on: [push, workflow_dispatch]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]

    steps:
      - name: Checkout git code
        uses: actions/checkout@v3

      - name: Run E2E Cypress tests
        uses: cypress-io/github-action@v4
        with:
          command: yarn cy:ci
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
